name: merlefisher
favicon: null
layout_spectrum: 0.3503906228579581
typography_spectrum: 0.6491350538562983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5432108098175377
  lightness: 0.03131137299351394
  saturation: 0.2980194005649537
  rhythmicContrast: 0.43857026216574013
purpose: []
