name: merlefisher
favicon: null
layout_spectrum: 0.3503906228579581
typography_spectrum: 0.6491350538562983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1f1f'
    - '#f8df36'
    - '#bbb7b2'
    - '#7e7e7e'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.2980194005649537
  rhythmicContrast: 0.43857026216574013
purpose: []
